source 'https://rubygems.org'

gem 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', ref: '2-4-stable'
gem 'spree_bootstrap', path: '../spree_bootstrap'

gemspec
